#!/bin/bash

YEAR=$1
MONTH=$2

if [[ -z $YEAR || -z $MONTH ]]
then
        YEAR=$(date +"%Y")
	MONTH=$(date +"%m")
fi

LOGS_PATH="/home/timbal/taller/logs"
COMPRESS_PATH="/home/timbal/taller/daily-logs"

REMOTE_IP="192.168.0.22"
REMOTE_USER="timbal2"
REMOTE_PATH="/home/timbal2/taller"
SSH_KEY_NAME="/home/timbal/taller/scripts/timbal2-server"

SERVICES_NAME=$(ls $COMPRESS_PATH)

for SERVICE in $SERVICES_NAME
do
	LOCAL_FILES="${COMPRESS_PATH}/${SERVICE}/*"
	FILE_COUNT=$(ls -1p $COMPRESS_PATH/$SERVICE | wc -l)
	if [ ! "$FILE_COUNT" -gt 0 ]
	then
		echo "Logs not found in ${COMPRESS_PATH}/${SERVICE}"
		continue
	fi

	DEST_FOLDER="${REMOTE_PATH}/${SERVICE}/${YEAR}/${MONTH}"

	ssh -i $SSH_KEY_NAME $REMOTE_USER@$REMOTE_IP "mkdir -p $DEST_FOLDER"

	scp -i $SSH_KEY_NAME $LOCAL_FILES $REMOTE_USER@$REMOTE_IP:$DEST_FOLDER

	rm ${COMPRESS_PATH}/${SERVICE}/* 2>/dev/null
	echo "Logs sent to remote server and deleted from local"
done

